version: '3.8'

services:
  mongo:
    image: mongo:6.0.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/instagram-replica
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: ["npm", "run", "dev"]

  seed:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/instagram-replica
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "seed"]
    entrypoint: ["sh", "-c", "while ! nc -z mongo 27017; do sleep 1; done; npm run seed"]

volumes:
  mongo-data:
